spring:
  application:
    name: Outsourcing_Project

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  error:
    include-message: always

jwt:
  secret:
    key: ${SECRET_KEY}

# ???? ?? ?? (?? ??)
# logging:
#   level:
#     org:
#       springframework:
#         security: trace
